"""empty message

Revision ID: aeeff22f9412
Revises: 
Create Date: 2023-05-18 14:35:04.339121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeeff22f9412'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('user_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_email')
    )
    op.create_table('wardrobes',
    sa.Column('wardrobe_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('wardrobe_name', sa.String(length=256), nullable=False),
    sa.Column('wardrobe_image', sa.String(), nullable=True),
    sa.Column('wardrobe_description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('wardrobe_id')
    )
    op.create_table('items',
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('item_color', sa.String(), nullable=False),
    sa.Column('item_category', sa.String(), nullable=False),
    sa.Column('item_suitability', sa.String(), nullable=False),
    sa.Column('item_price', sa.Float(), nullable=False),
    sa.Column('item_time', sa.DateTime(), nullable=False),
    sa.Column('item_season', sa.Enum('spring', 'summer', 'fall', 'winter', name='season_name'), nullable=False),
    sa.Column('wardrobe_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['wardrobe_id'], ['wardrobes.wardrobe_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('images',
    sa.Column('image_id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.PrimaryKeyConstraint('image_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    op.drop_table('items')
    op.drop_table('wardrobes')
    op.drop_table('users')
    # ### end Alembic commands ###
